/* VENTARA POS - Ticket POS estable */
(()=>{
  function getDb(){try{return window.db}catch(e){return null}}
  function safeToast(msg){try{if(typeof window.toast==='function')window.toast(msg)}catch(e){console.warn(msg)}}
  function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#39;')}
  function moneySafe(v){try{return typeof window.money==='function'?window.money(v):'$ '+Number(v||0).toLocaleString('es-CO')}catch(e){return '$ '+Number(v||0).toLocaleString('es-CO')}}
  function html(s){const d=getDb(),st=d?.settings||{};if(!s)return '<html><body>Ticket no disponible</body></html>';const logo=st.logo||window.VENTARA_LOGO||'',client=typeof window.clientName==='function'?window.clientName(s.clientId):((d?.clients||[]).find(c=>c.id===s.clientId)?.name||'Consumidor final');const items=(s.items||[]).map(i=>`<div class="r"><span>${esc(i.qty)} x ${esc(i.name)}</span><span>${moneySafe(i.qty*i.price)}</span></div>`).join('');const sub=(s.items||[]).reduce((a,i)=>a+Number(i.qty||0)*Number(i.price||0),0);return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(s.number||'Ticket POS')}</title><style>@page{size:80mm auto;margin:0}body{width:80mm;margin:0;padding:3mm;box-sizing:border-box;font:12px/1.25 "Courier New",monospace;color:#000}.c{text-align:center}.logo{max-width:48mm;max-height:22mm;object-fit:contain}.b{font-size:16px;font-weight:900}.sep{border-top:1px dashed #000;margin:6px 0}.r{display:flex;justify-content:space-between;gap:5px;margin:2px 0}.r span:first-child{max-width:54mm;word-break:break-word}.tot{font-size:15px;font-weight:900}.toolbar{position:fixed;top:0;left:0;width:100%;padding:8px;text-align:center;background:#eee;font:14px Arial,sans-serif}@media print{.toolbar{display:none}}</style></head><body><div class="toolbar"><button onclick="window.focus();window.print()">🖨 Imprimir</button> <button onclick="window.close()">Cerrar</button></div><div style="padding-top:42px"><div class="c">${logo?`<img class="logo" src="${esc(logo)}">`:''}<div class="b">${esc(st.business||'VENTARA POS')}</div>${st.legal?`<div>${esc(st.legal)}</div>`:''}${st.nit?`<div>NIT / ID: ${esc(st.nit)}</div>`:''}${st.city?`<div>${esc(st.city)}</div>`:''}${st.phone?`<div>Tel: ${esc(st.phone)}</div>`:''}${st.email?`<div>${esc(st.email)}</div>`:''}</div><div class="sep"></div><b>FACTURA POS ${esc(s.number||'')}</b><br>Fecha: ${esc(s.date||'')} ${esc(s.time||'')}<br>Cliente: ${esc(client)}<div class="sep"></div>${items}<div class="sep"></div><div class="r"><span>Subtotal</span><span>${moneySafe(sub)}</span></div>${Number(s.discount||0)>0?`<div class="r"><span>Descuento</span><span>${moneySafe(s.discount)}</span></div>`:''}<div class="r tot"><span>TOTAL</span><span>${moneySafe(s.total)}</span></div><div class="r"><span>Medio de pago</span><span>${esc(s.method||'')}</span></div><div class="sep"></div><div class="c">Gracias por su compra<br><b>${esc(st.business||'VENTARA POS')}</b></div></div><script>window.addEventListener('load',()=>setTimeout(()=>{try{window.focus();window.print()}catch(e){}},400));</script></body></html>`}
  function printTicket(id){const d=getDb(),s=d?.sales?.find(x=>x.id===id);if(!s)return safeToast('No se encontró la venta');const w=window.open('about:blank','_blank','width=460,height=850');if(!w)return safeToast('El navegador bloqueó la ventana del ticket. Permite ventanas emergentes para VENTARA POS.');w.document.open();w.document.write(html(s));w.document.close()}
  window.printTicket=printTicket;window.offerTicket=printTicket;
  let lastCount=0,watching=false;
  function watchSale(){if(watching)return;watching=true;const d=getDb();lastCount=Array.isArray(d?.sales)?d.sales.length:0;const started=Date.now();const timer=setInterval(()=>{const db2=getDb(),n=Array.isArray(db2?.sales)?db2.sales.length:0;if(n>lastCount){clearInterval(timer);watching=false;printTicket(db2.sales[0].id)}else if(Date.now()-started>15000){clearInterval(timer);watching=false}},150)}
  document.addEventListener('click',e=>{const b=e.target?.closest?.('button');if(!b)return;const t=(b.textContent||'').replace(/\s+/g,' ').toUpperCase();if(t.includes('CONFIRMAR')&&t.includes('REGISTRAR')&&t.includes('VENTA'))watchSale()},true);
})();
