from pathlib import Path
import re

path = Path('index.html')
html = path.read_text(encoding='utf-8')

new_quotes = r'''function renderQuotes(){document.getElementById('quotes').innerHTML=pageHead('Cotizaciones','Crea cotizaciones completas, compártelas y conviértelas en venta',`<button class="btn primary" onclick="openQuoteModal()">+ Cotización</button>`)+`<div class="card">${table(['Número','Fecha','Cliente','Total','Vigencia','Estado','Acción'],db.quotes.map(q=>`<tr><td><b>${q.number}</b></td><td>${q.date}</td><td>${clientName(q.clientId)}</td><td><b>${money(q.total)}</b></td><td>${q.validity||'—'}</td><td><span class="badge">${q.status}</span></td><td><button class="btn sm" onclick="viewQuote('${q.id}')">Ver</button> <button class="btn sm" onclick="printQuotePDF('${q.id}')">PDF</button> <button class="btn sm" onclick="quoteWhatsApp('${q.id}')">WhatsApp</button> <button class="btn sm" onclick="convertQuote('${q.id}')">Venta</button></td></tr>`).join(''),'Aún no hay cotizaciones. Crea la primera para varios productos.')}</div>`)}
let quoteDraftItems=[];
function openQuoteModal(){quoteDraftItems=[];openModal(`<h2>Nueva cotización</h2><p class="muted">Agrega todos los productos que el cliente solicitó. La cotización quedará guardada en la nube y podrás verla, imprimirla en PDF o compartirla por WhatsApp.</p><div class="form"><div class="field"><label>Cliente</label><select id="q_client">${db.clients.map(c=>`<option value="${c.id}">${c.name}${c.phone?' · '+c.phone:''}</option>`).join('')}</select></div><div class="field"><label>Vigencia hasta</label><input id="q_valid" type="date" value="${today()}"></div><div class="field" style="grid-column:1/-1"><label>Observaciones para el cliente</label><textarea id="q_notes" rows="2" placeholder="Ej.: Precios sujetos a disponibilidad. Tiempo de entrega 1 a 2 días."></textarea></div></div><div class="card" style="margin-top:15px;background:#f8fafc"><div class="form"><div class="field"><label>Producto</label><select id="q_prod">${db.products.filter(p=>p.active!==false).map(p=>`<option value="${p.id}">${p.name} · ${money(p.price)}</option>`).join('')}</select></div><div class="field"><label>Cantidad</label><input id="q_qty" type="number" min="0.01" step="0.01" value="1"></div><div class="field" style="align-self:end"><button class="btn primary" onclick="addQuoteItem()">+ Agregar producto</button></div></div><div id="quoteDraftItems" style="margin-top:12px"></div></div><div style="display:flex;justify-content:flex-end;gap:10px;align-items:center;margin-top:15px"><b>Total: <span id="quoteDraftTotal">${money(0)}</span></b><button class="btn primary" onclick="saveQuote()">Guardar cotización</button></div>`);renderQuoteDraftItems()}
function addQuoteItem(){let p=db.products.find(x=>x.id===v('q_prod')),qty=Number(v('q_qty'));if(!p)return toast('Selecciona un producto');if(!qty||qty<=0)return toast('La cantidad debe ser mayor que cero');let existing=quoteDraftItems.find(i=>i.productId===p.id);if(existing)existing.qty+=qty;else quoteDraftItems.push({productId:p.id,name:p.name,qty,price:p.price,cost:p.cost,unit:p.unit||'UND'});renderQuoteDraftItems()}
function removeQuoteItem(index){quoteDraftItems.splice(index,1);renderQuoteDraftItems()}
function renderQuoteDraftItems(){let el=document.getElementById('quoteDraftItems');let total=quoteDraftItems.reduce((a,i)=>a+i.qty*i.price,0);if(el)el.innerHTML=table(['Producto','Cantidad','Precio unitario','Subtotal','Acción'],quoteDraftItems.map((i,n)=>`<tr><td><b>${i.name}</b><br><small class="muted">${i.unit||''}</small></td><td>${i.qty}</td><td>${money(i.price)}</td><td>${money(i.qty*i.price)}</td><td><button class="btn sm danger" onclick="removeQuoteItem(${n})">Quitar</button></td></tr>`).join(''),'Agrega los productos solicitados por el cliente');let t=document.getElementById('quoteDraftTotal');if(t)t.textContent=money(total)}
function saveQuote(){let clientId=v('q_client'),validity=v('q_valid'),notes=v('q_notes').trim();if(!clientId)return toast('Selecciona un cliente');if(!quoteDraftItems.length)return toast('Agrega al menos un producto');let total=quoteDraftItems.reduce((a,i)=>a+i.qty*i.price,0),number='Q-'+String(db.quotes.length+1).padStart(6,'0');let x={id:uid('q'),number,date:today(),clientId,validity,status:'Borrador',total,notes,items:structuredClone(quoteDraftItems)};db.quotes.unshift(x);save();closeModal();renderQuotes();toast('Cotización completa guardada')}
function quoteFor(id){return db.quotes.find(x=>x.id===id)}
function quoteHtml(q){let c=db.clients.find(x=>x.id===q.clientId)||{name:'Consumidor final',doc:'',phone:'',email:''};return `<div class="quote-doc"><div class="quote-head"><div><img src="${db.settings.logo||VENTARA_LOGO}" class="quote-logo"><div><h1>${db.settings.business||'VENTARA POS'}</h1><div>${db.settings.legal||''}</div><div>NIT: ${db.settings.nit||''} · ${db.settings.city||''}</div><div>${db.settings.phone||''} · ${db.settings.email||''}</div></div></div><div class="quote-meta"><b>COTIZACIÓN</b><strong>${q.number}</strong><span>Fecha: ${q.date}</span><span>Vigencia: ${q.validity||'—'}</span></div></div><div class="quote-client"><b>Cliente</b><div>${c.name||'Consumidor final'}</div>${c.doc?`<div>Documento: ${c.doc}</div>`:''}${c.phone?`<div>Teléfono: ${c.phone}</div>`:''}${c.email?`<div>Correo: ${c.email}</div>`:''}</div><table class="quote-table"><thead><tr><th>Producto</th><th>Cant.</th><th>Valor unitario</th><th>Total</th></tr></thead><tbody>${(q.items||[]).map(i=>`<tr><td>${i.name}</td><td>${i.qty}</td><td>${money(i.price)}</td><td>${money(i.qty*i.price)}</td></tr>`).join('')}</tbody><tfoot><tr><td colspan="3">TOTAL COTIZADO</td><td>${money(q.total)}</td></tr></tfoot></table>${q.notes?`<div class="quote-notes"><b>Observaciones</b><p>${q.notes.replace(/\n/g,'<br>')}</p></div>`:''}<div class="quote-footer">Documento generado por VENTARA POS · Esta cotización no constituye una factura.</div></div>`}
function viewQuote(id){let q=quoteFor(id);if(!q)return;openModal(`<div>${quoteHtml(q)}<div class="actions" style="justify-content:flex-end;margin-top:15px"><button class="btn" onclick="copyQuoteText('${q.id}')">Copiar resumen</button><button class="btn" onclick="quoteWhatsApp('${q.id}')">WhatsApp</button><button class="btn primary" onclick="printQuotePDF('${q.id}')">Generar PDF</button></div></div>`)}
function quoteText(q){let c=db.clients.find(x=>x.id===q.clientId);return `COTIZACIÓN ${q.number}\n${db.settings.business||'VENTARA POS'}\nCliente: ${c?.name||'Consumidor final'}\nFecha: ${q.date}\nVigencia: ${q.validity||'—'}\n\n${(q.items||[]).map(i=>`• ${i.name} x ${i.qty}: ${money(i.qty*i.price)}`).join('\n')}\n\nTOTAL: ${money(q.total)}${q.notes?`\n\n${q.notes}`:''}`}
function copyQuoteText(id){let q=quoteFor(id);if(!q)return;navigator.clipboard?.writeText(quoteText(q)).then(()=>toast('Resumen copiado')).catch(()=>toast('No fue posible copiar automáticamente'))}
function quoteWhatsApp(id){let q=quoteFor(id);if(!q)return;let c=db.clients.find(x=>x.id===q.clientId);if(!c?.phone)return toast('El cliente no tiene teléfono registrado');if(q.status==='Borrador'){q.status='Enviada';save();renderQuotes()}let phone=String(c.phone).replace(/\D/g,'');if(phone.length===10)phone='57'+phone;window.open('https://wa.me/'+phone+'?text='+encodeURIComponent(quoteText(q)),'_blank');toast('Cotización preparada para WhatsApp')}
function printQuotePDF(id){let q=quoteFor(id);if(!q)return;let w=window.open('','_blank','width=1000,height=800');if(!w)return toast('El navegador bloqueó la ventana');w.document.write(`<html><head><title>${q.number} · Cotización</title><style>body{font-family:Arial,sans-serif;color:#172033;margin:0;padding:30px}.quote-doc{max-width:900px;margin:auto}.quote-head{display:flex;justify-content:space-between;gap:30px;border-bottom:3px solid #0ea5e9;padding-bottom:18px}.quote-head>div:first-child{display:flex;gap:14px;align-items:center}.quote-logo{width:170px;height:auto;object-fit:contain}.quote-head h1{margin:0 0 5px;font-size:24px}.quote-meta{text-align:right;display:flex;flex-direction:column;gap:4px}.quote-meta b{color:#0284c7;font-size:20px}.quote-meta strong{font-size:18px}.quote-client{margin:22px 0;padding:14px;background:#f1f5f9;border-radius:8px}.quote-table{width:100%;border-collapse:collapse}.quote-table th,.quote-table td{border-bottom:1px solid #dbe3ea;padding:10px;text-align:left}.quote-table th{background:#0f172a;color:white}.quote-table th:nth-child(n+2),.quote-table td:nth-child(n+2){text-align:right}.quote-table tfoot td{font-weight:700;font-size:16px;border-top:2px solid #0f172a}.quote-notes{margin-top:25px;padding:14px;border-left:4px solid #0ea5e9;background:#f8fafc}.quote-footer{margin-top:35px;padding-top:12px;border-top:1px solid #dbe3ea;color:#64748b;font-size:11px}@media print{@page{size:A4;margin:12mm}body{padding:0}.quote-doc{max-width:none}}</style></head><body>${quoteHtml(q)}<script>window.onload=()=>window.print()<\\/script></body></html>`);w.document.close()}
function convertQuote(id){let q=quoteFor(id);if(!q||q.status==='Convertida')return;posClient=q.clientId;cart=(q.items||[]).map(i=>({id:i.productId,qty:i.qty,price:i.price,cost:i.cost}));q.status='Convertida';save();showPage('pos');toast('Cotización cargada en POS')}
function renderCash('''

pattern = r'function renderQuotes\(\).*?function renderCash\('
updated, count = re.subn(pattern, lambda _: new_quotes, html, count=1, flags=re.S)
if count != 1:
    raise SystemExit('No se encontró el bloque de cotizaciones esperado')

path.write_text(updated, encoding='utf-8')
print('Quotation workflow patched successfully')
